#!/usr/bin/perl
#---------------------------------------------------
# ntirc: an insanely flexible IRC client.          |
# Copyright (c) 2011, the NoTrollPlzNet developers |
#---------------------------------------------------

use warnings; # WARNS ME WHEN IM WRONG!!!!!! =]
use strict;   # KEEPS ME HONEST!!!!!!!!!!!(:
use lib 'lib';

our %app = (
    name     => 'ntirc',
    version  => 'prerelease-dev',
    icon     => './img/nticon.png',
    location => (sub { require FindBin; sub FindBin::Bin(); $FindBin::Bin })->()
);

our ($loop, $irc); # IO::Async::Loop

my $interface     = 'Interface::Gtk2';
my $interfacename = $interface;
$interfacename    =~ s/::/\//g;
$interfacename   .= '.pm';
require $interfacename;
$interface->start();
